### ISSUE TITLE
Crashes on 1.13.1

### ISSUE THREAD

**Issue by fais3000** [NodeBB/nodebb-plugin-webhooks#2]
After upgrading from 1.12.2 to 1.13.1. This plugin causes nodebb to crash on start.

Database: Mongodb

`2020-01-07T22:59:08.993Z [4568/6499] - error: uncaughtException: Callback was already called.
Error: Callback was already called.
    at /var/www/discussimdb.com/nodebb/node_modules/async/dist/async.js:322:36
    at Immediate.callback (/var/www/discussimdb.com/nodebb/src/plugins/hooks.js:169:7)
    at runCallback (timers.js:757:11)
    at tryOnImmediate (timers.js:717:5)
    at processImmediate [as _immediateCallback] (timers.js:697:5) {"error":{},"stack":"Error: Callback was already called.\n    at /var/www/discussimdb.com/nodebb/node_modules/async/dist/async.js:322:36\n    at Immediate.callback (/var/www/discussimdb.com/nodebb/src/plugins/hooks.js:169:7)\n    at runCallback (timers.js:757:11)\n    at tryOnImmediate (timers.js:717:5)\n    at processImmediate [as _immediateCallback] (timers.js:697:5)","exception":true,"date":"Tue Jan 07 2020 22:59:08 GMT+0000 (UTC)","process":{"pid":6499,"uid":0,"gid":0,"cwd":"/var/www/discussimdb.com/nodebb","execPath":"/root/.nvm/versions/node/v9.5.0/bin/node","version":"v9.5.0","argv":["/root/.nvm/versions/node/v9.5.0/bin/node","/var/www/discussimdb.com/nodebb/app.js"],"memoryUsage":{"rss":174252032,"heapTotal":139104256,"heapUsed":107507840,"external":36482176}},"os":{"loadavg":[1.26806640625,0.87060546875,0.669921875],"uptime":10969581},"trace":[{"column":36,"file":"/var/www/discussimdb.com/nodebb/node_modules/async/dist/async.js","function":null,"line":322,"method":null,"native":false},{"column":7,"file":"/var/www/discussimdb.com/nodebb/src/plugins/hooks.js","function":"Immediate.callback","line":169,"method":"callback","native":false},{"column":11,"file":"timers.js","function":"runCallback","line":757,"method":null,"native":false},{"column":5,"file":"timers.js","function":"tryOnImmediate","line":717,"method":null,"native":false},{"column":5,"file":"timers.js","function":"processImmediate [as _immediateCallback]","line":697,"method":null,"native":false}]}
2020-01-07T22:59:08.994Z [4568/6499] - error: Callback was already called.
2020-01-07T22:59:08.995Z [4568/6499] - info: [app] Shutdown (SIGTERM/SIGINT) Initialised.`

Nodebb starts okay after Disabling the plugin by

```./nodebb reset -p nodebb-plugin-webhooks```
and 
```./nodebb build```

**Comment by barisusakli** [comment]
Thanks for reporting please install 1.0.9 and try again.

https://github.com/NodeBB/nodebb-plugin-webhooks/commit/ed6504bc857813db82212401f8ed8f3121b43a18

**Comment by fais3000** [comment]
@barisusakli The new version works! Thanks for the prompt fix.
